<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Infrastructure\Mcm.Authorizations.Infrastructure.csproj" />
    <ProjectReference Include="..\Application\Mcm.Authorizations.Application.csproj" />
    <ProjectReference Include="..\..\..\Shared\Infrastructure\Mcm.Shared.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
