// <auto-generated />
using System;
using Mcm.Contacts.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mcm.Contacts.Infrastructure.Migrations
{
    [DbContext(typeof(ContactDbContext))]
    [Migration("20260605113826_FixContact")]
    partial class FixContact
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("contacts")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mcm.Contacts.Domain.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssociatedCompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Cin")
                        .HasColumnType("text");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("contacts", "contacts");
                });

            modelBuilder.Entity("Mcm.Contacts.Domain.Entities.Contact", b =>
                {
                    b.OwnsMany("Mcm.Contacts.Domain.Entities.ContactValue", "Values", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ContactId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Data")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("PropertyId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("CompanyId");

                            b1.ToTable("ContactValue", "contacts");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.OwnsOne("Mcm.Shared.Domain.ValueObjects.Identity", "Identity", b1 =>
                        {
                            b1.Property<Guid>("ContactId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Position")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("position");

                            b1.HasKey("ContactId");

                            b1.ToTable("contacts", "contacts");

                            b1.WithOwner()
                                .HasForeignKey("ContactId");

                            b1.OwnsOne("Mcm.Shared.Domain.ValueObjects.Email", "Email", b2 =>
                                {
                                    b2.Property<Guid>("IdentityContactId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(255)
                                        .HasColumnType("character varying(255)")
                                        .HasColumnName("email");

                                    b2.HasKey("IdentityContactId");

                                    b2.ToTable("contacts", "contacts");

                                    b2.WithOwner()
                                        .HasForeignKey("IdentityContactId");
                                });

                            b1.OwnsOne("Mcm.Shared.Domain.ValueObjects.Name", "FirstName", b2 =>
                                {
                                    b2.Property<Guid>("IdentityContactId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(255)
                                        .HasColumnType("character varying(255)")
                                        .HasColumnName("first_name");

                                    b2.HasKey("IdentityContactId");

                                    b2.ToTable("contacts", "contacts");

                                    b2.WithOwner()
                                        .HasForeignKey("IdentityContactId");
                                });

                            b1.OwnsOne("Mcm.Shared.Domain.ValueObjects.Name", "LastName", b2 =>
                                {
                                    b2.Property<Guid>("IdentityContactId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(255)
                                        .HasColumnType("character varying(255)")
                                        .HasColumnName("last_name");

                                    b2.HasKey("IdentityContactId");

                                    b2.ToTable("contacts", "contacts");

                                    b2.WithOwner()
                                        .HasForeignKey("IdentityContactId");
                                });

                            b1.Navigation("Email")
                                .IsRequired();

                            b1.Navigation("FirstName")
                                .IsRequired();

                            b1.Navigation("LastName")
                                .IsRequired();
                        });

                    b.OwnsOne("Mcm.Shared.Domain.ValueObjects.Resource", "Image", b1 =>
                        {
                            b1.Property<Guid>("ContactId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AlternativeText")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("image_alternative_text");

                            b1.Property<int>("FileType")
                                .HasColumnType("integer")
                                .HasColumnName("image_file_type");

                            b1.Property<int>("StorageType")
                                .HasColumnType("integer")
                                .HasColumnName("image_storage_type");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("image_url");

                            b1.HasKey("ContactId");

                            b1.ToTable("contacts", "contacts");

                            b1.WithOwner()
                                .HasForeignKey("ContactId");
                        });

                    b.Navigation("Identity")
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
