### ============================================
### 2. COMPANY FEATURE
### ============================================

### Create Company - Subsidiary/ Contact
POST {{baseUrl}}/api/company
###Request:
{
  "name": string,
  "acronym": string?,
  "description": string?,
  "logo": Image,
  "isContact": bool,
  "isParent": guid?,
  "typeContactId": guid?,
  "SupplementaryValues: [
    {
      "propertyId": guid,
      "value": string
    }
  ],
}
### Response:
{
  "companyId": guid
}

### Get Company by Token - GET request
GET {{baseUrl}}/api/company/me
Authorization: Bearer {{token}}

### Response:
{
  "name": string,
  "acronym": string?,
  "description": string?,
  "logo": {
    "url": string,
    "storageType": string,
    "fileType": "Image",
    "alternativeText": string
  },
  "parent"?: {
    "Id": guid,
    "Name": string
  },
  "activitySector": [
    {
      "Id": guid,
      "Name": string
    }
  ],
  "SupplementaryValues": [
    {
      "categoryId": guid,
      "categoryName": string,
      "informations": [
        {
          "propertyId": guid,
          "propertyName": string,
          "value": string
        }
      ]
    }
  ]
}

### Get Company by ID - GET request
GET {{baseUrl}}/api/company/{id:Guid}
Authorization: Bearer {{token}}

### Response:
{
  "name": string,
  "acronym": string?,
  "description": string?,
  "logo": {
    "url": string,
    "storageType": string,
    "fileType": "Image",
    "alternativeText": string
  },
  "parent"?: {
    "Id": guid,
    "Name": string
  },
  "activitySector": [
    {
      "Id": guid,
      "Name": string
    }
  ],
  "SupplementaryValues": [
    {
      "categoryId": guid,
      "categoryName": string,
      "informations": [
        {
          "propertyId": guid,
          "propertyName": string,
          "value": string
        }
      ]
    }
  ]
}

### Update Company - PUT request
PUT {{baseUrl}}/api/company/{id:Guid}
Authorization: Bearer {{token}}
### Request:
{
  "name": string?,
  "acronym": string?,
  "description": string?,
  "logo": image?
}

### Response:
{
  "companyId": guid
}

### Update Company Value - POST request - By categoryId
PUT {{baseUrl}}/api/company/{id}/values
Authorization: Bearer {{token}}

### Request:
{
  "categoryId": Guid,
  "informations": [
    {
      "propertyId": guid,
      "value": string
    }
  ]
}
### Response:
{
  "companyId": guid
}

### Update Mutiple Company Value - POST request - By categoryId
PUT {{baseUrl}}/api/company/{id}/values
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

### Request:
{
  [
    {
      "categoryId": Guid,
      "informations": [
        {
          "propertyId": guid,
          "value": string
        }
      ]
    }
  ]
}
### Response:
{
  "companyId": guid
}

### Delete Company - DELETE request
DELETE {{baseUrl}}/api/company/{id:Guid}?force={force:bool}
Authorization: Bearer {{token}}


### ============================================
### 4. ROLE FEATURE
### ============================================

### Create Role - POST request
POST {{baseUrl}}/api/role
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

### Request:
{
  "title": string,
  "description": string?,
  "permissions": [
    {
      module: string,
      action: string
    }
  ],
  "companies": guid[]
}

### Response:
{
  "RoleId": "550e8400-e29b-41d4-a716-446655440010"
}


### Get All Roles - GET request
GET {{baseUrl}}/api/role
Authorization: Bearer {{token}}

### Response:
{
  "roles": [
    {
      "id": guid,
      "title": string,
      "count": int
    }
  ]
}
---

### Get Role by ID - GET request
GET {{baseUrl}}/api/role/{id:Guid}
Authorization: Bearer {{token}}

### Response:
{
  "id": guid,
  "title": string,
  "description": string?,
  "permissions": [
    {
      module: string,
      action: string
    }
  ]
}

---

### Update Role - PUT request
PUT {{baseUrl}}/api/role/{id:Guid}
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

# Request:
{
  "title": string,
  "description": string?,
  "permissions": [
    {
      module: string,
      action: string
    }
  ],
  "companies": guid[]
}

### Response:
{
  "roleId": guid
}


### Delete Role - DELETE request
DELETE {{baseUrl}}/api/role/{id:Guid}?force={force:bool}
Authorization: Bearer {{token}}

### Response:
### {
###   "success": true,
###   "code": 200
###   "data": null,
###   "message": "Role deleted successfully",
###   "meta": null
### }

---

### ============================================
### 5. TEAM MEMBER FEATURE
### ============================================

### Invite Team Member - POST request
POST {{baseUrl}}/api/company/{id}/teamMember/invite
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

### Request:
{
  "firstName": string,
  "lastName": string,
  "email": string,
  "roleId": Guid
}
### Response:
{
  "teamMemberId": guid
}

---

### Invitation Accepted - POST request
POST {{baseUrl}}/api/team-member/invitation_accepted?token={token}
Content-Type: {{contentType}}

### Request:
{
  "firstName": string,
  "lastName": string,
  "email": string,
  "password": string
}

### Response:
{
  "teamMemberId": guid
}

---

### Invitation Denied - POST request
POST {{baseUrl}}/api/teamMember/invitation_denied?token={token:string}

### Response:
### {
###   "success": true,
###   "code": 200
###   "data": null,
###   "message": "Invitation denied",
###   "meta": null
### }

---

### Get All Team Members - GET request
GET {{baseUrl}}/api/teamMember?page={page:int}&limit={limit:int}
Authorization: Bearer {{token}}

### Response:
{
  "teamMembers": [
    {
      "id": guid,
      "lastName": string,
      "firstName": string,
      "role": string,
      "isInvited": bool
    }
  ]
}

---

### Get Team Member by ID - GET request
GET {{baseUrl}}/api/teamMember/{id:Guid}
Authorization: Bearer {{token}}

### Response:
{
  "id": guid,
  "identity": {
    "firstName": string,
    "lastName": string,
    "email": string,
    "phoneNumber": string
  },
  "role": string,
  "image": {
    "storageType": string,
    "url": string,
    "alternativeText": string,
    "fileType": string
  },
  "lastLoginAt": datetime,
  "SupplementaryValues": [
    {
      "categoryId": guid,
      "categoryName": string,
      "informations": [
        {
          "propertyId": guid,
          "propertyName": string,
          "value": string
        }
      ]
    }
  ]
}

---

### Update Team Member Info - PUT request
PUT {{baseUrl}}/api/teamMember/{id:Guid}
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "firstName": string,
  "lastName": strin,
  "email": string,
}

### Response:
{
  "teamMemberId": guid
}

---

### Upload Team Member Photo - POST request (multipart/form-data)
POST {{baseUrl}}/api/teamMember/{id: guid}/photo
Authorization: Bearer {{token}}

### Request:
{
  "photo": Image
}

### Response:
{
  "image": {
    "storageType": string,
    "url": string,
    "alternativeText": string,
    "fileType": string
  }
}

