// <auto-generated />
using System;
using Mcm.Interactions.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mcm.Interactions.Infrastructure.Migrations
{
    [DbContext(typeof(InteractionDbContext))]
    [Migration("20260624090619_AddReport")]
    partial class AddReport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("interactions")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mcm.Interactions.Domain.Entities.Interaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDone")
                        .HasColumnType("boolean");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid?>("ReportId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReportId")
                        .IsUnique();

                    b.HasIndex("TypeId");

                    b.ToTable("interactions", "interactions");
                });

            modelBuilder.Entity("Mcm.Interactions.Domain.Entities.InteractionContact", b =>
                {
                    b.Property<Guid>("InteractionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("InteractionId", "ContactId");

                    b.ToTable("interaction_contacts", "interactions");
                });

            modelBuilder.Entity("Mcm.Interactions.Domain.Entities.InteractionMember", b =>
                {
                    b.Property<Guid>("InteractionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("InteractionId", "TeamMemberId");

                    b.ToTable("interaction_Members", "interactions");
                });

            modelBuilder.Entity("Mcm.Interactions.Domain.Entities.InteractionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LabelColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("interaction_interactionTypes", "interactions");
                });

            modelBuilder.Entity("Mcm.Interactions.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionPlan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("InteractionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("interaction_reports", "interactions");
                });

            modelBuilder.Entity("Mcm.Interactions.Domain.Entities.ReportContact", b =>
                {
                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("ReportId", "ContactId");

                    b.ToTable("report_contacts", "interactions");
                });

            modelBuilder.Entity("Mcm.Interactions.Domain.Entities.ReportMember", b =>
                {
                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("ReportId", "TeamMemberId");

                    b.ToTable("report_members", "interactions");
                });

            modelBuilder.Entity("Mcm.Interactions.Domain.Entities.TypeField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InteractionTypeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InteractionTypeId");

                    b.ToTable("interaction_typeFields", "interactions");
                });

            modelBuilder.Entity("Mcm.Interactions.Domain.Entities.Interaction", b =>
                {
                    b.HasOne("Mcm.Interactions.Domain.Entities.Report", "Report")
                        .WithOne("Interaction")
                        .HasForeignKey("Mcm.Interactions.Domain.Entities.Interaction", "ReportId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Mcm.Interactions.Domain.Entities.InteractionType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Mcm.Shared.Domain.ValueObjects.Resource", "Attachments", b1 =>
                        {
                            b1.Property<Guid>("InteractionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("AlternativeText")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ContentType")
                                .HasColumnType("text");

                            b1.Property<int>("FileType")
                                .HasColumnType("integer");

                            b1.Property<int>("StorageType")
                                .HasColumnType("integer");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("InteractionId", "Id");

                            b1.ToTable("interaction_attachments", "interactions");

                            b1.WithOwner()
                                .HasForeignKey("InteractionId");
                        });

                    b.OwnsOne("Mcm.Interactions.Domain.ValueObjects.DataTime", "Date", b1 =>
                        {
                            b1.Property<Guid>("InteractionId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("endDate");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("startDate");

                            b1.HasKey("InteractionId");

                            b1.ToTable("interactions", "interactions");

                            b1.WithOwner()
                                .HasForeignKey("InteractionId");
                        });

                    b.OwnsOne("Mcm.Shared.Domain.ValueObjects.Name", "Title", b1 =>
                        {
                            b1.Property<Guid>("InteractionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("title");

                            b1.HasKey("InteractionId");

                            b1.ToTable("interactions", "interactions");

                            b1.WithOwner()
                                .HasForeignKey("InteractionId");
                        });

                    b.OwnsMany("Mcm.Interactions.Domain.ValueObjects.FieldValue", "FieldsValues", b1 =>
                        {
                            b1.Property<Guid>("InteractionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("TypeFieldId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("InteractionId", "Id");

                            b1.ToTable("interaction_fieldsValues", "interactions");

                            b1.WithOwner()
                                .HasForeignKey("InteractionId");
                        });

                    b.OwnsOne("Mcm.Interactions.Domain.ValueObjects.Reminder", "Reminder", b1 =>
                        {
                            b1.Property<Guid>("InteractionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Repeat")
                                .HasColumnType("integer")
                                .HasColumnName("reminder_repeat");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("reminder_type");

                            b1.Property<double>("Value")
                                .HasColumnType("double precision")
                                .HasColumnName("reminder_value");

                            b1.HasKey("InteractionId");

                            b1.ToTable("interactions", "interactions");

                            b1.WithOwner()
                                .HasForeignKey("InteractionId");
                        });

                    b.Navigation("Attachments");

                    b.Navigation("Date")
                        .IsRequired();

                    b.Navigation("FieldsValues");

                    b.Navigation("Reminder")
                        .IsRequired();

                    b.Navigation("Report");

                    b.Navigation("Title")
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Mcm.Interactions.Domain.Entities.InteractionContact", b =>
                {
                    b.HasOne("Mcm.Interactions.Domain.Entities.Interaction", "Interaction")
                        .WithMany("InteractionContacts")
                        .HasForeignKey("InteractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interaction");
                });

            modelBuilder.Entity("Mcm.Interactions.Domain.Entities.InteractionMember", b =>
                {
                    b.HasOne("Mcm.Interactions.Domain.Entities.Interaction", "Interaction")
                        .WithMany("InteractionMembers")
                        .HasForeignKey("InteractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interaction");
                });

            modelBuilder.Entity("Mcm.Interactions.Domain.Entities.InteractionType", b =>
                {
                    b.HasOne("Mcm.Interactions.Domain.Entities.InteractionType", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.OwnsOne("Mcm.Shared.Domain.ValueObjects.Name", "Title", b1 =>
                        {
                            b1.Property<Guid>("InteractionTypeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("title");

                            b1.HasKey("InteractionTypeId");

                            b1.ToTable("interaction_interactionTypes", "interactions");

                            b1.WithOwner()
                                .HasForeignKey("InteractionTypeId");
                        });

                    b.Navigation("Parent");

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("Mcm.Interactions.Domain.Entities.Report", b =>
                {
                    b.OwnsMany("Mcm.Shared.Domain.ValueObjects.Resource", "Attachments", b1 =>
                        {
                            b1.Property<Guid>("ReportId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("AlternativeText")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ContentType")
                                .HasColumnType("text");

                            b1.Property<int>("FileType")
                                .HasColumnType("integer");

                            b1.Property<int>("StorageType")
                                .HasColumnType("integer");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ReportId", "Id");

                            b1.ToTable("report_attachments", "interactions");

                            b1.WithOwner()
                                .HasForeignKey("ReportId");
                        });

                    b.OwnsOne("Mcm.Interactions.Domain.ValueObjects.DataTime", "Date", b1 =>
                        {
                            b1.Property<Guid>("ReportId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("endDate");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("startDate");

                            b1.HasKey("ReportId");

                            b1.ToTable("interaction_reports", "interactions");

                            b1.WithOwner()
                                .HasForeignKey("ReportId");
                        });

                    b.OwnsOne("Mcm.Shared.Domain.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("ReportId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("name");

                            b1.HasKey("ReportId");

                            b1.ToTable("interaction_reports", "interactions");

                            b1.WithOwner()
                                .HasForeignKey("ReportId");
                        });

                    b.Navigation("Attachments");

                    b.Navigation("Date")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Mcm.Interactions.Domain.Entities.ReportContact", b =>
                {
                    b.HasOne("Mcm.Interactions.Domain.Entities.Report", "Report")
                        .WithMany("PresentContacts")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Mcm.Interactions.Domain.Entities.ReportMember", b =>
                {
                    b.HasOne("Mcm.Interactions.Domain.Entities.Report", "Report")
                        .WithMany("PresentMembers")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Mcm.Interactions.Domain.Entities.TypeField", b =>
                {
                    b.HasOne("Mcm.Interactions.Domain.Entities.InteractionType", "InteractionType")
                        .WithMany("Fields")
                        .HasForeignKey("InteractionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Mcm.Shared.Domain.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("TypeFieldId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("name");

                            b1.HasKey("TypeFieldId");

                            b1.ToTable("interaction_typeFields", "interactions");

                            b1.WithOwner()
                                .HasForeignKey("TypeFieldId");
                        });

                    b.Navigation("InteractionType");

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Mcm.Interactions.Domain.Entities.Interaction", b =>
                {
                    b.Navigation("InteractionContacts");

                    b.Navigation("InteractionMembers");
                });

            modelBuilder.Entity("Mcm.Interactions.Domain.Entities.InteractionType", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("Mcm.Interactions.Domain.Entities.Report", b =>
                {
                    b.Navigation("Interaction")
                        .IsRequired();

                    b.Navigation("PresentContacts");

                    b.Navigation("PresentMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
