<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\Domain\Mcm.Shared.Domain.csproj" />
    <ProjectReference Include="..\Domain\Mcm.Property.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\Application\Mcm.Shared.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
