// <auto-generated />
using System;
using Mcm.Authorizations.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mcm.Authorizations.Infrastructure.Migrations
{
    [DbContext(typeof(AuthorizationDbContext))]
    [Migration("20260612065409_FixRelationTm3")]
    partial class FixRelationTm3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("authorizations")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mcm.Authorizations.Domain.Entities.PasswordReset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TeamMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenHashed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PasswordResets", "authorizations");
                });

            modelBuilder.Entity("Mcm.Authorizations.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("permissions", "authorizations");
                });

            modelBuilder.Entity("Mcm.Authorizations.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("roles", "authorizations");
                });

            modelBuilder.Entity("Mcm.Authorizations.Domain.Entities.RoleCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_company", "authorizations");
                });

            modelBuilder.Entity("Mcm.Authorizations.Domain.Entities.RoleTeamMember", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "TeamMemberId");

                    b.HasIndex("TeamMemberId");

                    b.ToTable("role_teammember", "authorizations");
                });

            modelBuilder.Entity("Mcm.Authorizations.Domain.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InvitationToken")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("teammembers", "authorizations");
                });

            modelBuilder.Entity("Mcm.Authorizations.Domain.Entities.Permission", b =>
                {
                    b.HasOne("Mcm.Authorizations.Domain.Entities.Role", "Role")
                        .WithMany("Authorizations")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Mcm.Authorizations.Domain.Entities.RoleCompany", b =>
                {
                    b.HasOne("Mcm.Authorizations.Domain.Entities.Role", null)
                        .WithMany("RoleCompanies")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mcm.Authorizations.Domain.Entities.RoleTeamMember", b =>
                {
                    b.HasOne("Mcm.Authorizations.Domain.Entities.Role", "Role")
                        .WithMany("Members")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mcm.Authorizations.Domain.Entities.TeamMember", "TeamMember")
                        .WithMany("Roles")
                        .HasForeignKey("TeamMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("TeamMember");
                });

            modelBuilder.Entity("Mcm.Authorizations.Domain.Entities.TeamMember", b =>
                {
                    b.OwnsMany("Mcm.Authorizations.Domain.Entities.TeamMemberValue", "SupplValues", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Data")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("PropertyId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("TeamMemberId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("TeamMemberId");

                            b1.ToTable("TeamMemberValue", "authorizations");

                            b1.WithOwner()
                                .HasForeignKey("TeamMemberId");
                        });

                    b.OwnsOne("Mcm.Shared.Domain.ValueObjects.Identity", "Identity", b1 =>
                        {
                            b1.Property<Guid>("TeamMemberId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("email");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("last_name");

                            b1.Property<string>("Position")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("position");

                            b1.HasKey("TeamMemberId");

                            b1.ToTable("teammembers", "authorizations");

                            b1.WithOwner()
                                .HasForeignKey("TeamMemberId");
                        });

                    b.OwnsOne("Mcm.Shared.Domain.ValueObjects.Resource", "Image", b1 =>
                        {
                            b1.Property<Guid>("TeamMemberId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AlternativeText")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("image_alt");

                            b1.Property<string>("FileType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("image_file");

                            b1.Property<string>("StorageType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("image_storage");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("image_url");

                            b1.HasKey("TeamMemberId");

                            b1.ToTable("teammembers", "authorizations");

                            b1.WithOwner()
                                .HasForeignKey("TeamMemberId");
                        });

                    b.Navigation("Identity")
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("SupplValues");
                });

            modelBuilder.Entity("Mcm.Authorizations.Domain.Entities.Role", b =>
                {
                    b.Navigation("Authorizations");

                    b.Navigation("Members");

                    b.Navigation("RoleCompanies");
                });

            modelBuilder.Entity("Mcm.Authorizations.Domain.Entities.TeamMember", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
