// <auto-generated />
using System;
using Mcm.Company.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mcm.Company.Infrastructure.Migrations
{
    [DbContext(typeof(CompanyDbContext))]
    [Migration("20260608113418_FixCompany")]
    partial class FixCompany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Company")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mcm.Company.Domain.Entities.ActivitySector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ActivitySectors", "Company");
                });

            modelBuilder.Entity("Mcm.Company.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsContact")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TypeContactId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("TypeContactId");

                    b.ToTable("companies", "Company");
                });

            modelBuilder.Entity("Mcm.Company.Domain.Entities.CompanyActivity", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivitySectorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("CompanyId", "ActivitySectorId");

                    b.HasIndex("ActivitySectorId");

                    b.ToTable("company_activities", "Company");
                });

            modelBuilder.Entity("Mcm.Company.Domain.Entities.TypeContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TypeConvertTo")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TypeConvertTo");

                    b.ToTable("company_typecontacts", "Company");
                });

            modelBuilder.Entity("Mcm.Company.Domain.Entities.Company", b =>
                {
                    b.HasOne("Mcm.Company.Domain.Entities.Company", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mcm.Company.Domain.Entities.TypeContact", "TypeContact")
                        .WithMany()
                        .HasForeignKey("TypeContactId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.OwnsOne("Mcm.Shared.Domain.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name");

                            b1.HasKey("CompanyId");

                            b1.ToTable("companies", "Company");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.OwnsMany("Mcm.Company.Domain.Entities.CompanyValue", "SupplValues", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Data")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("PropertyId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("CompanyId");

                            b1.ToTable("CompanyValue", "Company");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.OwnsOne("Mcm.Shared.Domain.ValueObjects.Resource", "Logo", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AlternativeText")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("logo_alternative_text");

                            b1.Property<int>("FileType")
                                .HasColumnType("integer")
                                .HasColumnName("logo_file_type");

                            b1.Property<int>("StorageType")
                                .HasColumnType("integer")
                                .HasColumnName("logo_storage_type");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("logo_url");

                            b1.HasKey("CompanyId");

                            b1.ToTable("companies", "Company");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.Navigation("Logo");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("SupplValues");

                    b.Navigation("TypeContact");
                });

            modelBuilder.Entity("Mcm.Company.Domain.Entities.CompanyActivity", b =>
                {
                    b.HasOne("Mcm.Company.Domain.Entities.ActivitySector", "ActivitySector")
                        .WithMany()
                        .HasForeignKey("ActivitySectorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Mcm.Company.Domain.Entities.Company", "Company")
                        .WithMany("CompanyActivities")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivitySector");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Mcm.Company.Domain.Entities.TypeContact", b =>
                {
                    b.HasOne("Mcm.Company.Domain.Entities.TypeContact", "TypeConvertToNavigation")
                        .WithMany()
                        .HasForeignKey("TypeConvertTo")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.OwnsOne("Mcm.Shared.Domain.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("TypeContactId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name");

                            b1.HasKey("TypeContactId");

                            b1.ToTable("company_typecontacts", "Company");

                            b1.WithOwner()
                                .HasForeignKey("TypeContactId");
                        });

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("TypeConvertToNavigation");
                });

            modelBuilder.Entity("Mcm.Company.Domain.Entities.Company", b =>
                {
                    b.Navigation("CompanyActivities");
                });
#pragma warning restore 612, 618
        }
    }
}
